#pragma once

#ifdef __cplusplus
namespace libwamediacommon
{

extern "C"
{
#endif // __cplusplus

typedef enum 
{
  MP4_PROBLEM_NONE = 0,
  MP4_PROBLEM_STTS_CUMULATIVE_SAMPLE_COUNT,
  MP4_PROBLEM_CTTS_CUMULATIVE_SAMPLE_COUNT,
  MP4_PROBLEM_STSC_CUMULATIVE_SAMPLE_COUNT,
  MP4_PROBLEM_STSS_CUMULATIVE_SAMPLE_COUNT,
  MP4_PROBLEM_STSS_START_INDEX,
  MP4_PROBLEM_STSS_TABLE_DESCENDING_VALUES,
  MP4_PROBLEM_STSC_START_INDEX,
  MP4_PROBLEM_STSC_EXCEEDS_CHUNK_INDEX,
  MP4_PROBLEM_STTS_VS_DURATION_MISMATCH,
  //MP4_PROBLEM_SDTP_SAMPLE_COUNT_MISMATCH, // TBD later, if troubled files appear
  MP4_PROBLEM_MEDIA_VS_TRACK_DURATION_MISMATCH,
  MP4_PROBLEM_DECLARED_AUDIO_SAMPLING_RATE_MISMATCH,
  MP4_PROBLEM_DECLARED_AUDIO_NUMBER_OF_CHANNELS_MISMATCH,
  MP4_PROBLEM_INCORRECT_NOMINAL_VIDEO_DIMENSIONS,
  MP4_PROBLEM_INCORRECT_LAST_AVC_NAL_UNIT_SIZE,
  MP4_PROBLEM_EDIT_BOX_REMODELING_NEEDED,
  MP4_PROBLEM_CLAP_BOX_REMODELING_NEEDED,
  MP4_PROBLEM_STREAMIFYING_NEEDED,
  MP4_PROBLEM_COMPACTING_MDAT_PAYLOAD_NEEDED,
  MP4_PROBLEM_UNDOCUMENTED_APPENDED_BYTES,
  MP4_PROBLEM_SHORTER_LAST_TRIMMABLE_BOX,
  MP4_PROBLEM_VIDEO_TRACK_WITHOUT_STSS_TABLE,
  
  MPEG_DASH_PROBLEM_SEGMENT_VS_TRACK_DURATION_MISMATCH,
  MPEG_DASH_PROBLEM_SEGMENT_VS_MEDIA_DURATION_MISMATCH,
} eMP4_FORMAT_PROBLEM_TYPE;

typedef struct
{
  eMP4_FORMAT_PROBLEM_TYPE problemType;
  uint32_t                 nTrackIndex;

  // repair specific data
  uint32_t                 nDesiredNewValue;
} CMp4ProblemInfo;

typedef struct
{
  uint32_t nBoxType;
  uint64_t nFileOffset;
  uint64_t nBoxBytes;
} CBoxRepairInfo;

#ifdef __cplusplus
}

}; // namespace libwamediacommon
#endif // __cplusplus

