#pragma once

#ifdef __cplusplus
namespace libwamediacommon
{
#endif // __cplusplus

#define ERROR_FACILITY_EXTERNAL_CAUSE_ERRORS  (100)
#define ERROR_FACILITY_TOPOLOGY_PROBLEMS      (200)
#define ERROR_FACILITY_ARCHITECTURAL_PROBLEMS (300)
#define ERROR_FACILITY_AVSTREAM_PROBLEMS      (400)
#define ERROR_FACILITY_APP_SPECIFIC           (500)

typedef enum
{
  // Basic integrity checks (box integrity error codes)
  WAMEDIA_STATUS_COMPLETED = 0,

  // external cause error codes

  WAMEDIA_STATUS_INADEQUATE_SET_OF_INPUT_VALUES = ERROR_FACILITY_EXTERNAL_CAUSE_ERRORS + 1,
  WAMEDIA_STATUS_OUTPUT_FILE_OPEN_FAILED,
  WAMEDIA_STATUS_FILE_WRITING_ERROR,
  WAMEDIA_STATUS_FILE_TOO_SHORT_FOR_INTENDED_EXAMINATION,

  // topology flaws error codes
  WAMEDIA_STATUS_FILE_PREMATURE_END = ERROR_FACILITY_TOPOLOGY_PROBLEMS + 1,
  WAMEDIA_STATUS_MEMORY_ALLOCATION_FAILED,
  WAMEDIA_STATUS_INPUT_FILE_OPEN_FAILED,
  WAMEDIA_STATUS_FILE_READING_ERROR,

  // FLV topology errors
  WAMEDIA_STATUS_FLV_UNKNOWN_TOPOLOGY,
  WAMEDIA_STATUS_FLV_HEADER_WRONG_DATA_OFFSET,
  WAMEDIA_STATUS_FLV_WRONG_BACK_POINTER_VALUE,
  WAMEDIA_STATUS_FLV_UNKNOWN_OR_UNSUPPORTED_TAG_TYPE,
  WAMEDIA_STATUS_FLV_SCRIPT_DATA_PARSING_ERROR,
  WAMEDIA_STATUS_FLV_MUX_TIME_COORDINATES_ERROR,
  WAMEDIA_STATUS_FLV_OPTIMUM_MUXING_SCHEME_FAILURE,

  // MP4 topology errors
  WAMEDIA_STATUS_UNKNOWN_MP4_BOX_TOPOLOGY,
  WAMEDIA_STATUS_UNKNOWN_FRAGMENTED_MP4_TOPOLOGY,
  WAMEDIA_STATUS_MULTIPLE_MDAT_BOXES_FOUND,

  // architectural flaws error codes
  WAMEDIA_STATUS_UNSUPPORTED_BOX_VERSION = ERROR_FACILITY_ARCHITECTURAL_PROBLEMS + 1,
  WAMEDIA_STATUS_BOX_CONTENTS_INCOMPLETE,
  WAMEDIA_STATUS_MISSING_MANDATORY_BOX,
  WAMEDIA_STATUS_STTS_SAMPLE_COUNT_CHECK_ERROR,
  WAMEDIA_STATUS_CTTS_SAMPLE_COUNT_CHECK_ERROR,
  WAMEDIA_STATUS_SDTP_SAMPLE_COUNT_CHECK_ERROR,
  WAMEDIA_STATUS_STSS_TABLE_INCORRECT,
  WAMEDIA_STATUS_STSC_TABLE_INCORRECT,
  WAMEDIA_STATUS_STSC_CHUNK_INDEX_ERROR,
  WAMEDIA_STATUS_MALFORMED_CHUNKS_OFFSETS_TABLE,
  WAMEDIA_STATUS_MALFORMED_CHUNK_SIZE_TABLE,
  WAMEDIA_STATUS_MALFORMED_CHUNK_TOPOLOGY_INFO,
  WAMEDIA_STATUS_INCOMPLETE_TRAK_PLAYBACK_DURATION,
  WAMEDIA_STATUS_INCOMPLETE_MEDIA_PLAYBACK_DURATION,
  WAMEDIA_STATUS_INCOMPLETE_DASH_SEGMENT_PLAYBACK_DURATION,
  WAMEDIA_STATUS_PLAYBACK_DURATION_MISMATCH,
  WAMEDIA_STATUS_UNDEFINED_CHUNK_TO_MDAT_RELATIONSHIP,
  WAMEDIA_STATUS_IMPERFECT_CHUNKS_TILING,
  WAMEDIA_STATUS_WORK_IN_PROGRESS,

  // avstream verification error codes
  WAMEDIA_STATUS_MALFORMED_STREAM_SPECIFIC_BOX = ERROR_FACILITY_AVSTREAM_PROBLEMS + 1,
  WAMEDIA_STATUS_UNSUPPORTED_ENCRYPTED_MEDIA,
  WAMEDIA_STATUS_NO_EXPECTED_MEDIA_STREAMS_DETECTED_IN_FILE,
  WAMEDIA_STATUS_MISMATCHED_TRAK_MEDIA_PROPERTIES,
  WAMEDIA_STATUS_AVSTREAM_PACKING_ERROR,

  // App specific error codes
  // file trimming error codes
  WAMEDIA_STATUS_TRIMMING_BYTE_LIMIT_TOO_SMALL = ERROR_FACILITY_APP_SPECIFIC + 1,
  WAMEDIA_STATUS_ILLOGICAL_FILE_LAYOUT_CALCULATION,
  WAMEDIA_STATUS_BOX_TRANSFERRING_FAILED,

  // streamifying error codes
  WAMEDIA_STATUS_STREAMIFYING_INPUT_COORDINATES_ERROR,

  // stream extraction error codes
  WAMEDIA_STATUS_UNDEFINED_AVSTREAM_EXTRACTION,
  WAMEDIA_STATUS_STREAM_EXTRACTION_INPUT_COORDINATE_ERROR,
  
  // tracks removal error code
  WAMEDIA_STATUS_ATTEMPTED_REMOVAL_OF_INADEQUATE_NUMBER_OF_TRACKS,

  // mux analysis error codes
  WAMEDIA_STATUS_INCONSISTENT_TRACK_ID_MAPPING,
  WAMEDIA_STATUS_INCONSISTENT_CHUNK_SAMPLES_MAPPING,
  WAMEDIA_STATUS_INCONSISTENT_STTS_TABLE,
  WAMEDIA_STATUS_INCONSISTENT_CTTS_TABLE,
  
  // editing error codes
  WAMEDIA_STATUS_INCONSISTENT_EDIT_SETTINGS,
  WAMEDIA_STATUS_INCONSISTENT_TABLES_FORMING,
  
  // multiplexing and stream parsing specific error codes
  WAMEDIA_STATUS_MUX_STREAM_FINDER_INCONSISTENT_TRACK_INDEX_SETTING,
  WAMEDIA_STATUS_MUX_STREAM_FINDER_UNUSUAL_TOPOLOGY,
  WAMEDIA_STATUS_INSUFFICIENT_INPUT_DATA_AVAILABLE,
  WAMEDIA_STATUS_METADATA_TAG_PARSING_ERROR,
  WAMEDIA_STATUS_AAC_PARSING_ERROR_UNSUPPORTED_AAC_FLAVOR, // no ADIF, LOAS, LATM, or raw payload are supported
  WAMEDIA_STATUS_AAC_PARSING_ERROR_STREAM_FORMAT_ERROR,
  WAMEDIA_STATUS_AAC_PARSING_ERROR_FRAME_TOO_SHORT,
  WAMEDIA_STATUS_AAC_PARSING_ERROR_FRAME_TOO_LONG,
  WAMEDIA_STATUS_MP3_PARSING_ERROR_STREAM_FORMAT_ERROR,
  WAMEDIA_STATUS_MP3_PARSING_ERROR_FRAME_TOO_SHORT,
  WAMEDIA_STATUS_MP3_PARSING_ERROR_FRAME_TOO_LONG,
  WAMEDIA_STATUS_AMR_PARSING_ERROR_STREAM_FORMAT_ERROR,
  WAMEDIA_STATUS_QCELP_PARSING_ERROR_STREAM_FORMAT_ERROR,
  WAMEDIA_STATUS_H264_PARSING_ERROR_STREAM_FORMAT_ERROR,
  WAMEDIA_STATUS_H264_PARSING_ERROR_ADAPTING_TO_EMULATION_PREVENTION,
  WAMEDIA_STATUS_H264_NO_SEEKABLE_FRAMES_FOUND_AFTER_START_TIME,
  WAMEDIA_STATUS_H264_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_H263_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_MP4V_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_MP4V_ESDS_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_MP4A_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_MP4A_ESDS_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_SAMR_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_DAMR_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_SAWB_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_DAWB_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_SQCP_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_QT_DQCP_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_ROTATION_DATA_MUXING_COORDINATES_ERROR,
  WAMEDIA_STATUS_OGG_INCORRECT_CAPTURE_PATTERN,
  WAMEDIA_STATUS_OPUS_HEADER_TOO_SHORT,
  WAMEDIA_STATUS_INVALID_AUDIO_STREAM_TOPOLOGY,
  WAMEDIA_STATUS_INVALID_VIDEO_STREAM_TOPOLOGY,

  // mp4repair error codes
  WAMEDIA_STATUS_REPAIR_INPUT_COORDINATES_ERROR,
  WAMEDIA_STATUS_MP4_FLAVOR_REPAIR_NOT_SUPPORTED,
  WAMEDIA_STATUS_UNINITIALIZED_PROBLEMS_REPORTING,
  WAMEDIA_STATUS_PROBLEM_HARD_TO_FIX,
  WAMEDIA_STATUS_REPAIR_FAILURE,

  WAMEDIA_STATUS_VIDEO_ROTATION_FAILURE,

  // forensics specific error codes
  WAMEDIA_STATUS_FORENSIC_EVIDENCE_TYPE_UNSUPPORTED,
  WAMEDIA_STATUS_FORENSIC_EVIDENCE_GATHERING_FAILURE,

  // splicing specific error codes
  WAMEDIA_STATUS_SPLICING_FAILURE,
  WAMEDIA_STATUS_UNSUPPORTED_SPLICING_INPUT_FILE_FLAVOR,
  WAMEDIA_STATUS_FAILED_TO_IDENTIFY_AV_STREAM_TRACK_INDICES,
  WAMEDIA_STATUS_HETEROGENEOUS_INPUT_FILES_STREAMS_PRESENCE,
  WAMEDIA_STATUS_DISPARATE_AUDIO_STREAM_PARAMS_SPLICING_ERROR,
  WAMEDIA_STATUS_DISPARATE_VIDEO_STREAM_PARAMS_SPLICING_ERROR,

  // versioning specific error codes
  WAMEDIA_STATUS_INCORRECT_VERSION_BOX_BYTE_LENGTH,
  WAMEDIA_STATUS_INCORRECT_VERSION_BOX_STRUCTURE,
  WAMEDIA_STATUS_ABANDONING_REPAIR_OF_NON_OBSOLETE_VERSION,

  // edit list (EDTS/ELST box) error codes
  WAMEDIA_STATUS_EDIT_LIST_PLAYBACK_DURATION_INTERFERENCE,

  // demux error codes
  WAMEDIA_STATUS_ILLOGICAL_DEMUX_SETTINGS,

  WAMEDIA_STATUS_UNSUPPORTED_FEATURE

} WAMEDIA_STATUS;

#ifdef __cplusplus
}; // namespace libwamediacommon
#endif //__cplusplus


