#pragma once

#define ERROR_VIDEO_ENCODING_CAUSE_ERRORS			100
#define ERROR_AUDIO_ENCODING_CAUSE_ERRORS			200
#define ERROR_TRANSCODING_MUXING_CAUSE_ERRORS		300
#define ERROR_RTMP_CAUSE_ERRORS						400

namespace FBCapture {
  namespace Common {

    typedef enum {
      // Common error codes
      FBCAPTURE_STATUS_OK = 0,
      FBCAPTURE_STATUS_ENCODE_IS_NOT_READY,
      FBCAPTURE_STATUS_NO_INPUT_FILE,
      FBCAPTURE_STATUS_FILE_READING_ERROR,
      FBCAPTURE_STATUS_OUTPUT_FILE_OPEN_FAILED,

      // Video/Image encoding specific error codes
      FBCAPTURE_STATUS_UNSUPPORTED_GRAPHICS_CARD_DRIVER_VERSION = ERROR_VIDEO_ENCODING_CAUSE_ERRORS,
      FBCAPTURE_STATUS_ENCODE_INIT_FAILED,
      FBCAPTURE_STATUS_ENCODE_SET_CONFIG_FAILED,
      FBCAPTURE_STATUS_ENCODER_CREATION_FAILED,
      FBCAPTURE_STATUS_INVALID_TEXTURE_POINTER,
      FBCAPTURE_STATUS_CONTEXT_CREATION_FAILED,
      FBCAPTURE_STATUS_TEXTURE_CREATION_FAILED,
      FBCAPTURE_STATUS_TEXTURE_RESOURCES_COPY_FAILED,
      FBCAPTURE_STATUS_IO_BUFFER_ALLOCATION_FAILED,
      FBCAPTURE_STATUS_ENCODE_PICTURE_FAILED,
      FBCAPTURE_STATUS_ENCODE_FLUSH_FAILED,

      // WIC specific error codes
      FBCAPTURE_STATUS_WIC_SAVE_IMAGE_FAILED,

      // Audio encoding specific error codes
      FBCAPTURE_STATUS_AUDIO_DEVICE_ENUMERATION_FAILED = ERROR_AUDIO_ENCODING_CAUSE_ERRORS,
      FBCAPTURE_STATUS_AUDIO_CLIENT_INIT_FAILED,
      FBCAPTURE_STATUS_WRITTING_WAV_HEADER_FAILED,
      FBCAPTURE_STATUS_RELEASING_WAV_FAILED,

      // Transcoding and muxing specific error codes
      FBCAPTURE_STATUS_MF_CREATION_FAILED = ERROR_TRANSCODING_MUXING_CAUSE_ERRORS,
      FBCAPTURE_STATUS_MF_INIT_FAILED,
      FBCAPTURE_STATUS_MF_CREATING_WAV_FORMAT_FAILED,
      FBCAPTURE_STATUS_MF_TOPOLOGY_CREATION_FAILED,
      FBCAPTURE_STATUS_MF_TOPOLOGY_SET_FAILED,
      FBCAPTURE_STATUS_MF_TRANSFORM_NODE_SET_FAILED,
      FBCAPTURE_STATUS_MF_MEDIA_CREATION_FAILED,
      FBCAPTURE_STATUS_MF_HANDLING_MEDIA_SESSION_FAILED,

      // WAMEDIA muxing specific error codes
      FBCAPTURE_STATUS_WAMDEIA_MUXING_FAILED,

      // RTMP specific error codes
      FBCAPTURE_STATUS_INVALID_FLV_HEADER = ERROR_RTMP_CAUSE_ERRORS,
      FBCAPTURE_STATUS_INVALID_STREAM_URL,
      FBCAPTURE_STATUS_RTMP_CONNECTION_FAILED,
      FBCAPTURE_STATUS_RTMP_DISCONNECTED,
      FBCAPTURE_STATUS_SENDING_RTMP_PACKET_FAILED,


    } FBCAPTURE_STATUS;
  }
}
